### ISSUE TITLE
Use yeoman-generator-list instead of npm search in yo install ?

### ISSUE THREAD

**Issue by gaboesquivel** [yeoman/yo#361]
use yeoman-generator-list so that we:
1. don't duplicate filtering code
2. speed up generator search? I guess
3. have access to additional metadata, Eg. stars https://github.com/yeoman/yo/issues/352

related to https://github.com/yeoman/yeoman-generator-list/issues/30

**Comment by sindresorhus** [comment]
:+1: Already mentioned in https://github.com/yeoman/yo/issues/352, but better as a separate issue indeed.

**Comment by addyosmani** [comment]
Just adding a hearty :+1: to this.

**Comment by SBoudrias** [comment]
Let's make sure the list is stable before we go forward with this. We still have short outage of 2-3 minutes sometime when we update our cache.

**Comment by eddiemonge** [comment]
Since the new platforms have proven stable (except for some account/billing issues that I'm working out [trying to figure out how to switch from free trial to paid currently]) this can be a reality. These are the current blockers:

 - [ ] Document new deploy process for list [#34](https://github.com/yeoman/yeoman-generator-list/issues/34)
 - [ ] Custom subdomain for list [#33](https://github.com/yeoman/yeoman-generator-list/issues/33)
 - [ ] Add blacklist to the generator list [#30](https://github.com/yeoman/yeoman-generator-list/issues/30)

Additionally:
 - [ ] Give team members access to the two components that generate/serve the list

**Comment by JoshuaKGoldberg** [comment]
Related: #574. There's probably some unification work to be done around searching.
